cache:
  - node_modules
  -
environment:
  nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run dist:win

build: false
