os: unstable
cache:
  - node_modules
environment:
  nodejs_version: "16"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - npm run dist:win

build: off
shallow_clone: true
clone_depth: 1
